# Generated by Django 3.1.7 on 2021-10-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportbikes',
            name='userId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
