# Generated by Django 3.1.7 on 2021-10-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportbikes_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportbikes',
            name='userId',
        ),
    ]
