# Generated by Django 3.2.8 on 2021-10-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_reportbikes_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbikes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
