# Generated by Django 3.2.8 on 2021-11-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_reportbikes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportbikes',
            name='drop',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportbikes',
            name='pickup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportbikes',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportbikes',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
