# Generated by Django 3.2.7 on 2021-09-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_feedback_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='bikeCode',
        ),
    ]
