# Generated by Django 3.2.8 on 2021-10-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_register_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
