# Generated by Django 3.2.7 on 2021-10-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('bikeId', models.IntegerField()),
                ('date', models.DateField()),
                ('startTime', models.TimeField(auto_now=True)),
                ('endTime', models.TimeField()),
            ],
        ),
    ]
