# Generated by Django 3.2.7 on 2021-10-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renttable',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
