# Generated by Django 3.2.7 on 2021-10-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20211011_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renttable',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='renttable',
            name='endTime',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='renttable',
            name='startTime',
            field=models.TimeField(default=None),
        ),
    ]
