# Generated by Django 3.2.7 on 2021-10-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20211011_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renttable',
            name='bikeId',
        ),
        migrations.RemoveField(
            model_name='renttable',
            name='userId',
        ),
    ]
