# Generated by Django 3.2.7 on 2021-10-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20211011_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renttable',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='renttable',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='renttable',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
