# Generated by Django 3.1.7 on 2021-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20211012_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renttable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
