# Generated by Django 3.1.7 on 2021-10-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_auto_20211014_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='renttable',
            name='rentLocation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='renttable',
            name='returnLocation',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
