# Generated by Django 3.1.7 on 2021-10-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_auto_20211020_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='renttable',
            name='bikeId',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='renttable',
            name='charges',
            field=models.IntegerField(default=None),
        ),
    ]
