# Generated by Django 3.1.7 on 2021-10-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_auto_20211020_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renttable',
            name='charges',
            field=models.IntegerField(null=True),
        ),
    ]
