# Generated by Django 3.1.7 on 2021-10-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_auto_20211020_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='renttable',
            name='userId',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
