# Generated by Django 3.2.8 on 2021-10-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_renttable_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='renttable',
            name='wallet',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='renttable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
